language: minimal
branches:
  # Travis is configured to build branches and PRs. Need to
  # restrict branch builds to just master branch, otherwise
  # PRs from same repo are built twice.
  only:
    - master
script:
  - sudo apt-get install graphviz
  - bin/travis_tests