---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Free-tier web hosting."
Parameters:
  SshKeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
  VPC:
    Type: "AWS::EC2::VPC::Id"
  Subnet:
    Type: "AWS::EC2::Subnet::Id"
# DnsApiKey:
#   Description: "DNS-update API key."
#   Type: "AWS::SecretsManager::Secret"
#   NoEcho: true
#   Properties:
Resources:
  Server:
    Type: "AWS::EC2::Instance"
    Properties:
      # Ubuntu Server 18.04 LTS (HVM), SSD Volume Type
      ImageId: "ami-0bbe6b35405ecebdb"
      InstanceType: "t2.micro"
      KeyName:
        Ref: "SshKeyName"
      SubnetId:
        Ref: "Subnet"
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash
          echo startup script running.
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group."
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: "0.0.0.0/0"
    # - IpProtocol: tcp
    #   FromPort: 80
    #   ToPort: 80
    #   CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
      - IpProtocol: "tcp"
        CidrIp: "0.0.0.0/0"
Outputs:
  PublicIp:
    Value: !GetAtt 'Server.PublicIp'